#!/bin/sh

echo -n Try to bring eth0 interface up......>/dev/ttySTM0

if [ -f /etc/eth0-setting ] ; then
	source /etc/eth0-setting
	
	if grep -q " / nfs " /etc/mtab ; then
		echo -n NFS root ... > /dev/ttySTM0
	else
		DEV_ADDR=`cat /sys/class/net/eth0/address`
	#	if [ "$DEV_ADDR" = "00:00:00:00:00:00" ]; then
			ifconfig eth0 down
			ifconfig eth0 hw ether $MAC
	#	fi
		
		ifconfig eth0 $IP netmask $Mask up
		route add default gw $Gateway
		
	fi
fi
