#!/bin/sh

echo "Starting rcS..."

echo "++ Mounting filesystem"
mkdir -p /dev/pts
mkdir -p /dev/i2c
mount -a

#echo "++ Setting up eth0"
#/etc/init.d/ifconfig-eth0


echo "++ Setting up mdev"

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

# the device driver is not creating this node, so for now
# create the devcfg device node manually

#if [ ! -e /dev/xdevcfg ]
#then
#	mknod /dev/xdevcfg c 259 0
#fi

echo "++ Starting telnet daemon"
#telnetd -l /bin/sh
telnetd -l /bin/login

#echo "++ Starting http daemon"
#httpd -h /var/www

echo "++ Starting ftp daemon"
tcpsvd 0:21 ftpd ftpd -w /&

#echo "++ Starting dropbear ssh"
#dropbear
# running the application

echo "mounting flash"
#mount -t jffs2 /dev/mtdblock4 /mnt/servo

#echo "start PPC_Loader"
#loader &


echo "rcS Complete"
